/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import Datos.AlumnosDAO;
import Dominio.Alumnos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leelu
 */
public class Mantenimiento_Alumnos extends javax.swing.JInternalFrame {
DefaultTableModel modelo1; 
    /**
     * Creates new form Mantenimiento_Alumnos
     */
    public Mantenimiento_Alumnos() {
        initComponents();
        limpio.setVisible(false);
        modelo1=new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DIRECCION");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EMAIL");
        modelo1.addColumn("ESTATUS");
        tabla1.setModel(modelo1);
        String datos[]= new String[6];
        AlumnosDAO dao = new  AlumnosDAO();
        List<Alumnos> alumnos = dao.select();
        for (Alumnos alumno : alumnos) {       
               datos[0]=alumno.getCodigo();
               datos[1]=alumno.getNombre();
               datos[2]=alumno.getDireccion();
               datos[3]=alumno.getTelefono();
               datos[4]=alumno.getEmail();
               datos[5]=alumno.getEstatus();
               modelo1.addRow(datos);
               tabla1.setModel(modelo1);
               }
    }
    public void limpiar() {
        carnet.setText("");
        nombre.setText("");
        direccion.setText("");
        telefono.setText("");
        email.setText("");
        activo.setSelected(false);
        inactivo.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        carnet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        activo = new javax.swing.JRadioButton();
        inactivo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        limpio = new javax.swing.JRadioButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jLabel1.setText("Carnet:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Direccion:");

        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefono:");

        jLabel5.setText("Email:");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jButton1.setText("ELIMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("GUARDAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("MODIFICAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla1);

        buttonGroup1.add(activo);
        activo.setText("ACTIVO");

        buttonGroup1.add(inactivo);
        inactivo.setText("INACTIVO");

        jLabel6.setText("ESTATUS:");

        buttonGroup1.add(limpio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carnet, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(nombre)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(direccion))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(activo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inactivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limpio)))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(activo)
                            .addComponent(inactivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(limpio))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

            if (carnet.getText().length() != 0&&nombre.getText().length() != 0&&direccion.getText().length() != 0&&telefono.getText().length() != 0&&email.getText().length() != 0&&activo.isSelected()||inactivo.isSelected()) {
            AlumnosDAO alumnosDAO = new AlumnosDAO();
            Alumnos alumnoInsertar = new Alumnos();
            alumnoInsertar.setCodigo(carnet.getText());
            alumnoInsertar.setNombre(nombre.getText());
            alumnoInsertar.setDireccion(direccion.getText());
            alumnoInsertar.setTelefono(telefono.getText());
            alumnoInsertar.setEmail(email.getText());
            if (activo.isSelected()) {
            alumnoInsertar.setEstatus("1");
            }
            if (inactivo.isSelected()) {
            alumnoInsertar.setEstatus("0");
            }
            alumnosDAO.insert(alumnoInsertar);
            JOptionPane.showMessageDialog(null, "Modulo registrado correctamente");
            }
            
 /*-----------------------------------------------------------------------------------------------*/
            
            modelo1=new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CARNET");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DIRECCION");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EMAIL");
        modelo1.addColumn("ESTATUS");
        tabla1.setModel(modelo1);
        String datos[]= new String[6];
        AlumnosDAO dao = new  AlumnosDAO();
        List<Alumnos> alumnos = dao.select();
        for (Alumnos alumno : alumnos) {       
               datos[0]=alumno.getCodigo();
               datos[1]=alumno.getNombre();
               datos[2]=alumno.getDireccion();
               datos[3]=alumno.getTelefono();
               datos[4]=alumno.getEmail();
               datos[5]=alumno.getEstatus();
               modelo1.addRow(datos);
               tabla1.setModel(modelo1);
               }
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AlumnosDAO sedesDAO = new AlumnosDAO();
                Alumnos AlumnoConsultar = new Alumnos();
                AlumnoConsultar.setCodigo(carnet.getText());
                AlumnoConsultar = sedesDAO.query(AlumnoConsultar);
                nombre.setText(AlumnoConsultar.getNombre());
                direccion.setText(AlumnoConsultar.getDireccion());
                telefono.setText(AlumnoConsultar.getTelefono());
                email.setText(AlumnoConsultar.getEmail());
                if ("1".equals(AlumnoConsultar.getEstatus()) ) {
                activo.setSelected(true);
                }
                if ("0".equals(AlumnoConsultar.getEstatus())) {
                inactivo.setSelected(true);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AlumnosDAO sedesDAO = new AlumnosDAO();
        Alumnos AlumnoActualizar = new Alumnos();
        AlumnoActualizar.setCodigo(carnet.getText());
        AlumnoActualizar.setNombre(nombre.getText());
        AlumnoActualizar.setDireccion(direccion.getText());
        AlumnoActualizar.setTelefono(telefono.getText());
        AlumnoActualizar.setEmail(email.getText());
        if (activo.isSelected()) {
            AlumnoActualizar.setEstatus("1");
            }
            if (inactivo.isSelected()) {
            AlumnoActualizar.setEstatus("0");
           }
        sedesDAO.update(AlumnoActualizar);
        JOptionPane.showMessageDialog(null, "Modulo actualizado correctamente");
        
 /*-----------------------------------------------------------------------------------------------*/
            
            modelo1=new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DIRECCION");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EMAIL");
        modelo1.addColumn("ESTADO");
        tabla1.setModel(modelo1);
        String datos[]= new String[6];
        AlumnosDAO dao = new  AlumnosDAO();
        List<Alumnos> alumnos = dao.select();
        for (Alumnos alumno : alumnos) {       
               datos[0]=alumno.getCodigo();
               datos[1]=alumno.getNombre();
               datos[2]=alumno.getDireccion();
               datos[3]=alumno.getTelefono();
               datos[4]=alumno.getEmail();
               datos[5]=alumno.getEstatus();
               modelo1.addRow(datos);
               tabla1.setModel(modelo1);
               }
                limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Alumnos alumnosEliminar = new Alumnos();
        AlumnosDAO alumnosDAO = new AlumnosDAO();
        alumnosEliminar.setCodigo(carnet.getText());
        alumnosDAO.delete(alumnosEliminar);
        JOptionPane.showMessageDialog(null, "Perfil Eliminado.");    
        
 /*-----------------------------------------------------------------------------------------------*/
            
            modelo1=new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DIRECCION");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EMAIL");
        modelo1.addColumn("ESTADO");
        tabla1.setModel(modelo1);
        String datos[]= new String[6];
        AlumnosDAO dao = new  AlumnosDAO();
        List<Alumnos> alumnos = dao.select();
        for (Alumnos alumno : alumnos) {       
               datos[0]=alumno.getCodigo();
               datos[1]=alumno.getNombre();
               datos[2]=alumno.getDireccion();
               datos[3]=alumno.getTelefono();
               datos[4]=alumno.getEmail();
               datos[5]=alumno.getEstatus();
               modelo1.addRow(datos);
               tabla1.setModel(modelo1);
               }
                limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carnet;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton inactivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton limpio;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
